#!/bin/bash
#
# Locally build one or more rpms via 'osc build' (for a single
# repository/arch combination) from their package's working
# directories locally checked out from a Build Service.
#
# Optionally switches the source service URL to consume local sources.
# To enable this feature, you should ensure that an executable called
# 'source-dir-for' is on your $PATH, which accepts a Build Service
# working directory as the only parameter, and outputs the absolute
# path of the corresponding locally checked out source repository,
# which can then be consumed by the tar_scm source service.

me=`basename $0`

usage () {
    # Call as: usage [EXITCODE] [USAGE MESSAGE]
    exit_code=1
    if [[ "$1" == [0-9] ]]; then
        exit_code="$1"
        shift
    fi
    if [ -n "$1" ]; then
        echo "$*" >&2
        echo
    fi

    cat <<EOF >&2
Usage: $me [options] BSDIR [BSDIR ...]
Options:
  -d, --disabledrun      Run \`osc service disabledrun' before build
  -l, --local-source     Switch tar_scm source service url to file://SRCDIR
                         as returned by 'source-dir-for BSDIR'.  Implies -d.
  -r, --revision=REV     Switch tar_scm source service revision to REV.
                         Implies -d.
  -R, --repository=REPO  Build for repository REPO
  -a, --arch=ARCH        Build for arch ARCH
  -o, --offline          (option passed to osc build)
  -h, --help             Show this help
EOF
    exit "$exit_code"
}

parse_opts () {
    disabledrun=
    local_source=
    offline=
    revision=

    while [ -n "$1" ]; do
        case "$1" in
            -h|--help)
                usage 0
                ;;
            -o)
                offline=-o
                shift
                ;;
            -d|--disabledrun)
                disabledrun=y
                shift
                ;;
            -l|--local-source)
                local_source=y
                disabledrun=y
                shift
                ;;
            -r|--revision)
                revision="$2"
                disabledrun=y
                shift 2
                ;;
            -R|--repository)
                repository="$2"
                shift 2
                ;;
            -a|--arch)
                arch="$2"
                shift 2
                ;;
            *)
                break
                ;;
        esac
    done

    if [ $# = 0 ]; then
        usage "You must specify at least one rpm to build."
    fi

    if [ -n "$arch" ] && [ -z "$repository" ]; then
        usage "Cannot specify arch without repository."
    fi

    bs_dirs=( "$@" )
}

die () {
    echo "$*; aborting." >&2
    exit 1
}

tweak_source_service () {
    local BS_pkg_dir="$1"

    if ! find_source_service_for_package "$BS_pkg_dir"; then
        echo "Couldn't find source service at $src_svc"
        if [ -n "$local_source" ]; then
            echo "  ignoring -l for $BS_pkg_dir"
        fi
        if [ -n "$revision" ]; then
            echo "  ignoring -r for $BS_pkg_dir"
        fi
        return 1
    fi

    if ! src_svc_temp=$( mktemp "${src_svc}.build-rpms.XXXXXXXX" ); then
        die "Couldn't make temporary backup of $src_svc"
    fi
    cp "$src_svc" "$src_svc_temp"

    if [ -n "$local_source" ]; then
        if ! switch_source_service_url "$BS_pkg_dir"; then
            die "Failed to switch source service for $BS_pkg_dir"
        fi
    fi

    if [ -n "$revision" ]; then
        if ! switch_source_service_revision "$BS_pkg_dir"; then
            die "Failed to switch source service for $BS_pkg_dir"
        fi
    fi
}

find_source_service_for_package () {
    local BS_pkg_dir="$1"
    src_svc="$BS_pkg_dir/_service"

    if ! [ -e "$src_svc" ]; then
        return 1
    fi

    return 0
}

switch_source_service_url () {
    local BS_pkg_dir="$1"

    if ! src_dir=$( source-dir-for "$BS_pkg_dir" ); then
        die "Running source-dir-for $BS_pkg_dir failed; aborting."
    fi

    url="file://$src_dir"
    tweak_param_value "url" "$url"
}

switch_source_service_revision () {
    local BS_pkg_dir="$1"
    tweak_param_value "revision" "$revision"
}

tweak_param_value () {
    local param="$1" new_value="$2"

    perl -Mstrict -wlni -e '
      my $param = q{'"$param"'};
      if (m!(\s*<param name="'"$param"'">)(.+)(</param>)!) {
          my $new_value = q{'"$new_value"'};
          my $old_value = $2;
          if ($old_value ne $new_value) {
              print "$1$new_value$3";
              print STDERR "Switched $param from $old_value to $new_value";
          }
          else {
              print;
              print STDERR "$param is set to: $old_value";
          }
      }
      else {
        print
      }' "$src_svc"
}

build_rpm () {
    local BS_pkg_dir="$1"

    if [ ! -d "$BS_pkg_dir" ]; then
        die "$BS_pkg_dir does not exist; aborting."
    fi

    cd $BS_pkg_dir

    if [ -n "$local_source" -o -n "$revision" ]; then
        tweak_source_service "$BS_pkg_dir"
    fi

    if [ -n "$disabledrun" ]; then
        if ! osc service disabledrun; then
            die "disabledrun failed; aborting."
        fi
    fi

    if [ -e "$src_svc_temp" ]; then
        mv "$src_svc_temp" "$src_svc"
    fi

    d="${BS_pkg_dir#$HOME/}"
    rpm_out_dir="$HOME/tmp/build-rpms/${d//\//_}"

    mkdir -p "$rpm_out_dir"
    find "$rpm_out_dir" -name \*.rpm | xargs -r rm

    if ! osc build -k "$rpm_out_dir" $offline $repository $arch; then
        die "osc build failed; aborting."
    fi

    echo "rpms saved in $rpm_out_dir"
}

main () {
    parse_opts "$@"

    for bs_dir in "${bs_dirs[@]}"; do
        bs_dir=$( cd "$bs_dir" && pwd ) || die "Invalid directory $bs_dir"
        build_rpm "$bs_dir"
    done
}

main "$@"
