#!/bin/bash
#pkg patchinfo by dlovasko@suse.com

#un/comment for debug/release
set -x

#try to run osc patchinfo
osc patchinfo &> /dev/null
retcode=$?

if [ $retcode = "0" ] 
then
	exit 0
else
	if [ -e ./patchinfo/_patchinfo ]
	then
		$EDITOR ./patchinfo/_patchinfo
	else
		echo "This command must be called in a checked out project or patchinfo package."
		exit 1
	fi
fi
	
 