#!/bin/bash

# Attach to existing tmux session or create new one with given name

SESSION="${1}"

if [ -z ${SESSION} ]; then
	echo "Usage:"
	echo "	${0##*/} <session_name>"
	exit 1
fi;

if tmux has-session -t "${SESSION}" 2>/dev/null; then
	exec tmux attach-session -t "${SESSION}"
fi
#else
#XXX: here we can do session-specific configuration
tmux new-session -s "${SESSION}"
